name: telemed_neurondata
description: Aplicativo de chamadas dÃ¡ telemed neurondata. 
repository: https://github.com/mining-information-for-you/app_telemed_client

publish_to: 'none'

version: 2.0.0+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  logger: ^1.1.0
  http: ^0.13.4
  go_router: ^10.0.0
  flutter_hooks: ^0.20.0
  indexed: ^0.0.8
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
